name: deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.8.0
          run_install: true
      - name: run build
        env:
          NODE_ENV: production
        run: |
          pnpm run clean
          pnpm run build
      - name: upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
