name: lint
on:
  push:
    branches-ignore:
      - master
  pull_request: {}

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.8.0
          run_install: true
      - name: run lint
        run: pnpm run eslint

  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.8.0
          run_install: true
      - name: run lint
        run: pnpm run stylelint
