name: test
on:
  push: {}
  pull_request: {}

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode:
          - production
          - development
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.8.0
          run_install: true
      - name: run ${{ matrix.mode }} build
        env:
          NODE_ENV: ${{ matrix.mode }}
        run: |
          pnpm run clean
          pnpm run build
